proxy:

  listen:
    address: "0.0.0.0"
    port: 8081

  services:

    - name: my-service
      domain: my-service.my-company.com
      hosts:
        - address: "172.17.0.3"
          port: 9091
        - address: "172.17.0.7"
          port: 9092